/// End-to-end parity test for the pure-Dart AECMOS pipeline
/// (example/aecmos/) against the Python reference
/// (microsoft/AEC-Challenge aecmos.py, librosa + onnxruntime).
///
/// test/aecmos_reference.json is generated by tool/gen_aecmos_reference.py
/// and carries, besides the final features and scores, every intermediate
/// pipeline stage for the mic signal — the tests below assert them in
/// pipeline order (window -> padding -> frame-0 power -> mel filterbank ->
/// mel frame -> dB -> normalized features -> markers -> model input ->
/// scores), so the first failing test names the diverging stage.
@TestOn('vm')
library;

import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:test/test.dart';

import '../example/aecmos/aecmos_scorer.dart';
import '../example/aecmos/mel_spectrogram.dart';

double _maxAbsDiff(List<double> got, List<dynamic> wantJson) {
  final want = wantJson.cast<num>();
  expect(got.length, want.length, reason: 'length mismatch');
  var max = 0.0;
  for (var i = 0; i < got.length; i++) {
    final d = (got[i] - want[i]).abs();
    if (d > max) max = d;
  }
  return max;
}

/// Max per-element relative difference, with tiny reference values floored at
/// `floorFraction` of the reference maximum so float32 noise in near-zero
/// bins does not blow up the ratio.
double _maxRelDiff(List<double> got, List<dynamic> wantJson,
    {double floorFraction = 1e-6}) {
  final want = wantJson.cast<num>();
  expect(got.length, want.length, reason: 'length mismatch');
  var maxWant = 0.0;
  for (final w in want) {
    if (w.abs() > maxWant) maxWant = w.abs().toDouble();
  }
  final floor = floorFraction * maxWant;
  var max = 0.0;
  for (var i = 0; i < got.length; i++) {
    final d = (got[i] - want[i]).abs() / math.max(want[i].abs(), floor);
    if (d > max) max = d;
  }
  return max;
}

Float32List _floats(dynamic j) =>
    Float32List.fromList([for (final v in j as List) (v as num).toDouble()]);

void main() {
  final refFile = File('test/aecmos_reference.json');
  if (!refFile.existsSync()) {
    throw StateError('test/aecmos_reference.json missing — run '
        '.venv/bin/python tool/gen_aecmos_reference.py');
  }
  final ref = jsonDecode(refFile.readAsStringSync()) as Map<String, dynamic>;

  final sr = ref['sampling_rate'] as int;
  final dftSize = ref['dft_size'] as int;
  final nFft = dftSize + 1;
  final hop = dftSize ~/ 2;
  final signals = ref['signals'] as Map<String, dynamic>;
  final lpb = _floats(signals['lpb']);
  final mic = _floats(signals['mic']);
  final enh = _floats(signals['enh']);
  final inter = ref['intermediates'] as Map<String, dynamic>;

  final home = Platform.environment['HOME'] ?? '';
  final modelPath =
      '$home/.cache/onnx_runtime_dart_models/${ref['model'] as String}';
  final modelMissing = !File(modelPath).existsSync();
  final skipModel =
      modelMissing ? 'AECMOS model not found at $modelPath' : false;

  final front = MelFrontEnd(sr: sr, nFft: nFft, hopLength: hop);

  test('stage 1: periodic Hann window', () {
    final d = _maxAbsDiff(front.window, inter['hann_window'] as List);
    expect(d, lessThan(1e-12), reason: 'window max abs diff $d');
  });

  test('stage 2: centered constant padding', () {
    final padded = front.padCentered(mic);
    final head = padded.sublist(0, 600);
    final d = _maxAbsDiff(head, inter['padded_head'] as List);
    expect(d, lessThan(1e-12), reason: 'padded head max abs diff $d');
  });

  test('stage 3: frame 0 power spectrum', () {
    final power = front.framePower(front.padCentered(mic), 0);
    final d = _maxRelDiff(power, inter['frame0_power'] as List);
    expect(d, lessThan(1e-3), reason: 'frame 0 power max rel diff $d');
  });

  test('stage 4: mel filterbank (Slaney scale and norm)', () {
    final dRow =
        _maxAbsDiff(front.melFilterRow(0), inter['mel_fb_row0'] as List);
    expect(dRow, lessThan(1e-6), reason: 'filterbank row 0 max abs diff $dRow');
    final dSums =
        _maxAbsDiff(front.melFilterRowSums(), inter['mel_fb_rowsums'] as List);
    expect(dSums, lessThan(1e-6), reason: 'row sums max abs diff $dSums');
  });

  test('stage 5: mel power frame 0', () {
    final mel = front.applyMel(front.framePower(front.padCentered(mic), 0));
    final d = _maxRelDiff(mel, inter['mel_frame0'] as List);
    expect(d, lessThan(1e-3), reason: 'mel frame 0 max rel diff $d');
  });

  test('stage 6: power_to_db (ref=max, amin=1e-10, top_db=80)', () {
    final spec = front.melSpectrogram(mic);
    final dbRef = powerToDb(spec);
    final wantRef = (inter['db_ref'] as num).toDouble();
    expect((dbRef - wantRef).abs() / wantRef, lessThan(1e-4),
        reason: 'dB reference (max power): got $dbRef, want $wantRef');
    final frame0 = [for (var m = 0; m < 160; m++) spec[m].toDouble()];
    final d = _maxAbsDiff(frame0, inter['db_frame0'] as List);
    expect(d, lessThan(0.01), reason: 'dB frame 0 max abs diff $d dB');
  });

  test('stage 7: normalized mel features (mic, full)', () {
    final feats = aecmosMelFeatures(mic, sr: sr, nFft: nFft, hopLength: hop);
    final micFeatures = ref['mic_features'] as Map<String, dynamic>;
    final shape = (micFeatures['shape'] as List).cast<int>();
    expect(melFrameCount(mic.length, nFft, hop), shape[0]);
    expect(feats.length, shape[0] * shape[1]);
    final dFrame0 = _maxAbsDiff([for (var m = 0; m < 160; m++) feats[m]],
        inter['features_frame0_norm'] as List);
    expect(dFrame0, lessThan(1e-3),
        reason: 'normalized frame 0 max abs diff $dFrame0');
    final d = _maxAbsDiff(feats, micFeatures['data'] as List);
    expect(d, lessThan(1e-3), reason: 'full mic features max abs diff $d');
  });

  test('stage 8: scenario marker frames (st, lpb channel)', () {
    final scorer = AecmosScorer(modelPath);
    final (:feats, :frames) = scorer.buildFeatures('st', lpb, mic, enh);
    final markerStart = inter['marker_rows_start'] as int;
    expect(frames, markerStart + 40, reason: 'marker frames not appended');
    final head = [
      for (var i = 0; i < 400; i++) feats[markerStart * 160 + i].toDouble()
    ];
    final d = _maxAbsDiff(head, inter['marker_head_st'] as List);
    expect(d, lessThan(1e-12), reason: 'lpb marker block max abs diff $d');
  }, skip: skipModel);

  test('stage 9: stacked model input [1, 3, frames, 160] (st)', () {
    final scorer = AecmosScorer(modelPath);
    final (feats: feats, frames: _) = scorer.buildFeatures('st', lpb, mic, enh);
    final head = [for (var i = 0; i < 160; i++) feats[i].toDouble()];
    final d = _maxAbsDiff(head, inter['model_input_slice'] as List);
    expect(d, lessThan(1e-3), reason: 'model input head max abs diff $d');
  }, skip: skipModel);

  test('stage 10: MOS scores for st, nst, dt', () {
    final scorer = AecmosScorer(modelPath);
    final scores = ref['scores'] as Map<String, dynamic>;
    for (final talkType in ['st', 'nst', 'dt']) {
      final want = scores[talkType] as Map<String, dynamic>;
      final got = scorer.score(talkType, lpb, mic, enh);
      expect(got.echoMos, closeTo((want['echo_mos'] as num).toDouble(), 0.01),
          reason: '$talkType echo MOS');
      expect(got.otherMos, closeTo((want['other_mos'] as num).toDouble(), 0.01),
          reason: '$talkType other MOS');
    }
  }, skip: skipModel);
}
