/// Replays every ORT-oracle fixture in test/fixtures/ through the Dart
/// runtime and asserts numeric parity with native ONNX Runtime.
///
/// Fixtures are generated by `tool/gen_fixtures.py` (see that file for the
/// directory format). Each op/attribute combination gets its own fixture, so
/// a failure here names the exact op configuration that diverged from ORT.
@TestOn('vm')
library;

import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:onnx_runtime_dart/onnx_runtime_dart.dart';
import 'package:test/test.dart';

/// Max absolute element difference tolerated vs the ORT oracle. Both sides
/// compute in float32; this only absorbs non-associative rounding (e.g. our
/// summation order differing from MLAS's blocked kernels).
const _tolerance = 2e-5;

Tensor _tensorFromJson(Map<String, dynamic> j) {
  final shape = (j['shape'] as List).cast<int>();
  final data = j['data'] as List;
  if (j['dtype'] == 'int64') {
    return Tensor.int64(
        Int64List.fromList(data.map((v) => (v as num).toInt()).toList()),
        shape);
  }
  return Tensor.float(
      Float32List.fromList([
        for (final v in data)
          v is String ? double.parse(v) : (v as num).toDouble()
      ]),
      shape);
}

void main() {
  final fixturesDir = Directory('test/fixtures');
  if (!fixturesDir.existsSync()) {
    throw StateError('test/fixtures/ missing — run tool/gen_fixtures.py '
        '(needs .venv, see that file\'s docstring)');
  }
  final cases = fixturesDir.listSync().whereType<Directory>().toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  for (final dir in cases) {
    final name = dir.uri.pathSegments.lastWhere((s) => s.isNotEmpty);
    test('ORT parity: $name', () {
      final model =
          OnnxModel.fromBytes(File('${dir.path}/model.onnx').readAsBytesSync());
      final j = jsonDecode(File('${dir.path}/case.json').readAsStringSync())
          as Map<String, dynamic>;
      final inputs = (j['inputs'] as Map<String, dynamic>)
          .map((k, v) => MapEntry(k, _tensorFromJson(v)));
      final expected = (j['expected'] as Map<String, dynamic>)
          .map((k, v) => MapEntry(k, _tensorFromJson(v)));

      final got = model.run(inputs, expected.keys.toList());

      expected.forEach((outName, want) {
        final have = got[outName]!;
        expect(have.shape, want.shape, reason: '$name/$outName shape mismatch');
        if (want.dtype == DType.int64) {
          expect(have.asIntList(), want.asIntList(),
              reason: '$name/$outName int values mismatch');
          return;
        }
        final w = want.asFloatList(), h = have.asFloatList();
        double maxAbs = 0, maxMag = 0;
        int at = -1;
        for (int k = 0; k < w.length; k++) {
          if (!w[k].isFinite) {
            expect(h[k].isNaN ? w[k].isNaN : h[k] == w[k], isTrue,
                reason: '$name/$outName non-finite mismatch at $k');
            continue;
          }
          expect(h[k].isFinite, isTrue,
              reason: '$name/$outName unexpected non-finite at $k');
          final d = (w[k] - h[k]).abs();
          if (d > maxAbs) {
            maxAbs = d;
            at = k;
          }
          if (w[k].abs() > maxMag) maxMag = w[k].abs();
        }
        // Mixed tolerance: ops whose outputs are large-magnitude sums (STFT
        // bins, integer accumulators) legitimately differ by float rounding
        // proportional to the value scale.
        final tolerance = j['expected'][outName]['dtype'] == 'float16' ? 2e-3 : _tolerance;
        final tol = math.max(tolerance, tolerance * maxMag);
        expect(maxAbs, lessThanOrEqualTo(tol),
            reason: '$name/$outName max|Δ|=$maxAbs at flat index $at '
                '(ort=${at >= 0 ? w[at] : '-'}, dart=${at >= 0 ? h[at] : '-'}, '
                'scale=$maxMag)');
        // Cosine similarity as a second, scale-aware signal.
        double dot = 0, nw = 0, nh = 0;
        for (int k = 0; k < w.length; k++) {
          dot += w[k] * h[k];
          nw += w[k] * w[k];
          nh += h[k] * h[k];
        }
        if (nw > 0 && nh > 0) {
          final cos = dot / (math.sqrt(nw) * math.sqrt(nh));
          expect(cos, greaterThan(0.999999),
              reason: '$name/$outName cosine=$cos');
        }
      });
    });
  }
}
