"""Generate structural audit metadata from ONNX/ORT's official schemas.

Run with onnx==1.22.0 and onnxruntime==1.29.0. This records schema validity,
not a claim that every kernel implements every configuration of that schema.
"""
import json
import re
from pathlib import Path
import onnx
from onnxruntime.capi._pybind_state import get_all_operator_schema

root = Path(__file__).resolve().parents[1]
source = (root / 'lib/src/onnx_graph.dart').read_text()
names = set(re.findall(r"case '([^']+)'", source)) - {'then_branch', 'else_branch'}
names |= {'Attention', 'RMSNormalization'}
names = {n for n in names if not n.startswith('_')}
ms = {'GroupQueryAttention', 'MultiHeadAttention', 'MatMulNBits',
      'SkipSimplifiedLayerNormalization', 'RotaryEmbedding'}
schemas = []
for s in onnx.defs.get_all_schemas_with_history():
    if s.domain == '' and s.name in names:
        schemas.append(s)
for s in get_all_operator_schema():
    if (s.domain == 'com.microsoft' and s.name in ms) or (s.domain == '' and s.name == 'SimplifiedLayerNormalization'):
        schemas.append(s)
data = {}
handled = {}
cases = list(re.finditer(r"case '([^']+)':", source))
pending = []
for i, match in enumerate(cases):
    body = source[match.end():cases[i+1].start() if i+1 < len(cases) else len(source)]
    pending.append(match.group(1))
    if not re.sub(r'//[^\n]*|\s+', '', body):
        continue
    found = set(re.findall(r"(?:attrs\w*|_attrsFor\(node\))\.get\w+\('([^']+)'", body))
    for name in pending:
        handled.setdefault(name, set()).update(found)
    pending = []
handled['Constant'] = {'value','value_int','value_ints','value_float','value_floats'}
handled.setdefault('Attention',set()).add('softmax_precision')
handled.setdefault('RMSNormalization',set()).add('stash_type')
handled.setdefault('Split',set()).add('num_outputs')
# Accuracy level is an implementation hint; this kernel always uses FLOAT.
handled.setdefault('MatMulNBits',set()).add('accuracy_level')
handled.setdefault('If',set()).update({'then_branch','else_branch'})
handled.setdefault('Loop',set()).add('body')
handled.setdefault('Scan',set()).update({'body','num_scan_inputs','scan_input_axes','scan_input_directions','scan_output_axes','scan_output_directions'})

def default(attr):
    a = attr.default_value if hasattr(attr, 'default_value') else onnx.AttributeProto.FromString(attr._default_value)
    if not a.type:
        return None
    value = onnx.helper.get_attribute_value(a)
    if isinstance(value, bytes):
        value = value.decode('utf8')
    if isinstance(value, list):
        value = [v.decode('utf8') if isinstance(v,bytes) else v for v in value]
    return value if isinstance(value, (int,float,str,list)) else None

for s in schemas:
    attrs = {k: [int(v.type), v.required, default(v)] for k, v in s.attributes.items()}
    constraints = {c.type_param_str:list(c.allowed_type_strs) for c in s.type_constraints}
    def parameter(p):
        t = p.type_str if hasattr(p,'type_str') else p.typeStr
        return [constraints.get(t,[t]), int(p.option)]
    data.setdefault(f'{s.domain}:{s.name}', []).append({
        'version': s.since_version,
        'attributes': attrs,
        'handledAttributes': sorted(handled.get(s.name, set())),
        'inputTypes': [parameter(p) for p in s.inputs],
        'minInputs': s.min_input, 'maxInputs': s.max_input,
        'minOutputs': s.min_output, 'maxOutputs': s.max_output,
        'requiredInputs': [i for i, p in enumerate(s.inputs) if int(p.option) == 0],
    })
for versions in data.values():
    versions.sort(key=lambda v: v['version'])
payload = json.dumps(data, sort_keys=True, separators=(',', ':'))
(root / 'lib/src/operator_schemas.dart').write_text(
    '// Generated by tool/gen_operator_schemas.py; do not edit.\n'
    '// ONNX 1.22.0 / ONNX Runtime 1.29.0 schema metadata.\n'
    "const operatorSchemasJson = r'''" + payload + "''';\n")
print(f'Generated {len(data)} operator families')
